# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20161019_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='imager_profile.Photographer'),
        ),
    ]
