# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20160923_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='photographer_profile',
        ),
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imager_profile.Photographer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Street Address 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='State'),
        ),
    ]
