# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0004_auto_20160923_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='has_portfolios',
            field=models.BooleanField(default=False),
        ),
    ]
