# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='appature',
        ),
        migrations.AddField(
            model_name='photo',
            name='aperture',
            field=models.CharField(blank=True, max_length=64, verbose_name='Aperture'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
