# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20160915_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='likes_cheese',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is_public?'),
        ),
    ]
