# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_auto_20161017_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='aperture',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Aperture'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='camera',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Camera'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Focal Length'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='height_field',
            field=models.IntegerField(blank=True, default='0', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latitude',
            field=models.IntegerField(blank=True, default='0', verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lens',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Lens'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='longitude',
            field=models.IntegerField(blank=True, default='0', verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='shutter_speed',
            field=models.IntegerField(blank=True, default='0', verbose_name='Shutter Speed'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width_field',
            field=models.IntegerField(blank=True, default='0', verbose_name='Width'),
        ),
    ]
